// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Varejo.Data;

#nullable disable

namespace Varejo.Migrations
{
    [DbContext(typeof(VarejoDbContext))]
    partial class VarejoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parametro", b =>
                {
                    b.Property<int>("IdParametroMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametroMovimento"));

                    b.Property<int>("TipoMovimentoAvariaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimentoCompraId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimentoEntradaBonificacaoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimentoVendaId")
                        .HasColumnType("int");

                    b.HasKey("IdParametroMovimento");

                    b.HasIndex("TipoMovimentoAvariaId");

                    b.HasIndex("TipoMovimentoCompraId");

                    b.HasIndex("TipoMovimentoEntradaBonificacaoId");

                    b.HasIndex("TipoMovimentoVendaId");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("RecebimentoItem", b =>
                {
                    b.Property<int>("IdRecebimentoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecebimentoItem"));

                    b.Property<string>("CodigoProdutoFornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EhBonificacao")
                        .HasColumnType("bit");

                    b.Property<int>("ProdutoEmbalagemId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RecebimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdRecebimentoItem");

                    b.HasIndex("ProdutoEmbalagemId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RecebimentoId");

                    b.ToTable("RecebimentosItem");
                });

            modelBuilder.Entity("Varejo.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DescricaoCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("DescricaoCategoria")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Varejo.Models.ConfiguracaoEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Logotipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesEmpresa");
                });

            modelBuilder.Entity("Varejo.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("PessoaId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Varejo.Models.EspecieMovimento", b =>
                {
                    b.Property<int>("IdEspecieMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecieMovimento"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DescricaoEspecieMovimento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdEspecieMovimento");

                    b.ToTable("EspeciesMovimento");
                });

            modelBuilder.Entity("Varejo.Models.EspecieTitulo", b =>
                {
                    b.Property<int>("IdEspecieTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecieTitulo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEspecieTitulo");

                    b.ToTable("EspeciesTitulo");
                });

            modelBuilder.Entity("Varejo.Models.EstoqueConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EstoqueMaximo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("EstoquesConfig");
                });

            modelBuilder.Entity("Varejo.Models.EstoqueSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Estoque")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstoquesSnapshot");
                });

            modelBuilder.Entity("Varejo.Models.Familia", b =>
                {
                    b.Property<int>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamilia"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeFamilia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFamilia");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("NomeFamilia")
                        .IsUnique();

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("Varejo.Models.FormaPagamento", b =>
                {
                    b.Property<int>("IdFormaPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormaPagamento"));

                    b.Property<string>("DescricaoFormaPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormaPagamento");

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("Varejo.Models.FornecedorFamilia", b =>
                {
                    b.Property<int>("IdFornecedorFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFornecedorFamilia"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("IdFornecedorFamilia");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("FornecedoresFamilia");
                });

            modelBuilder.Entity("Varejo.Models.HistoricoPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecoAntigo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoNovo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("HistoricosPreco");
                });

            modelBuilder.Entity("Varejo.Models.HistoricoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("EspecieMovimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstoqueAntes")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EstoqueDepois")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MovimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeMovimento")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TipoMovimentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("EspecieMovimentoId");

                    b.HasIndex("MovimentoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TipoMovimentoId");

                    b.ToTable("HistoricosProduto");
                });

            modelBuilder.Entity("Varejo.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Varejo.Models.InventarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoEmbalagemId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeContada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QuantidadeSistema")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.HasIndex("ProdutoEmbalagemId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("InventariosItem");
                });

            modelBuilder.Entity("Varejo.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NomeMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMarca");

                    b.HasIndex("NomeMarca")
                        .IsUnique();

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Varejo.Models.Movimento", b =>
                {
                    b.Property<int>("IdMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimento"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Documento")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("RecebimentoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimentoId")
                        .HasColumnType("int");

                    b.Property<int?>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("IdMovimento");

                    b.HasIndex("PessoaId");

                    b.HasIndex("RecebimentoId");

                    b.HasIndex("TipoMovimentoId");

                    b.HasIndex("VendaId");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("Varejo.Models.PagamentoTitulo", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPagamento"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TituloFinanceiroId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPagamento");

                    b.HasIndex("TituloFinanceiroId");

                    b.ToTable("PagamentosTitulo");
                });

            modelBuilder.Entity("Varejo.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("EhCliente")
                        .HasColumnType("bit");

                    b.Property<bool>("EhFornecedor")
                        .HasColumnType("bit");

                    b.Property<bool>("EhJuridico")
                        .HasColumnType("bit");

                    b.Property<bool>("EhUsuario")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeRazao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TratamentoFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPessoa");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Varejo.Models.PrazoPagamento", b =>
                {
                    b.Property<int>("IdPrazoPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrazoPagamento"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntervaloDias")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("int");

                    b.HasKey("IdPrazoPagamento");

                    b.ToTable("PrazosPagamento");
                });

            modelBuilder.Entity("Varejo.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CustoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("EstoqueAtual")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EstoqueInicial")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdProduto");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("NomeProduto")
                        .IsUnique();

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoCusto", b =>
                {
                    b.Property<int>("IdProdutoCusto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdutoCusto"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhCustoAtual")
                        .HasColumnType("bit");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("RecebimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCustoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdProdutoCusto");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RecebimentoId");

                    b.ToTable("ProdutosCusto");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoEmbalagem", b =>
                {
                    b.Property<int>("IdProdutoEmbalagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdutoEmbalagem"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEmbalagemId")
                        .HasColumnType("int");

                    b.HasKey("IdProdutoEmbalagem");

                    b.HasIndex("Ean")
                        .IsUnique();

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TipoEmbalagemId");

                    b.ToTable("ProdutosEmbalagem");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoFornecedorVinculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProdutoNoFornecedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescricaoNoFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutosFornecedorVinculo");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoMovimento", b =>
                {
                    b.Property<int>("IdProdutoMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdutoMovimento"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MovimentoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoEmbalagemId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProdutoMovimento");

                    b.HasIndex("MovimentoId");

                    b.HasIndex("ProdutoEmbalagemId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutosMovimento");
                });

            modelBuilder.Entity("Varejo.Models.Recebimento", b =>
                {
                    b.Property<int>("IdRecebimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecebimento"));

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("PrazoPagamentoId")
                        .HasColumnType("int");

                    b.HasKey("IdRecebimento");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("PrazoPagamentoId");

                    b.ToTable("Recebimentos");
                });

            modelBuilder.Entity("Varejo.Models.RecebimentoXmlLog", b =>
                {
                    b.Property<int>("IdXmlLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdXmlLog"));

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecebimentoId")
                        .HasColumnType("int");

                    b.Property<string>("XmlCaminho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdXmlLog");

                    b.HasIndex("RecebimentoId");

                    b.ToTable("RecebimentosXmlLog");
                });

            modelBuilder.Entity("Varejo.Models.TipoEmbalagem", b =>
                {
                    b.Property<int>("IdTipoEmbalagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEmbalagem"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DescricaoTipoEmbalagem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Multiplicador")
                        .HasColumnType("int");

                    b.HasKey("IdTipoEmbalagem");

                    b.HasIndex("DescricaoTipoEmbalagem")
                        .IsUnique();

                    b.ToTable("TiposEmbalagem");
                });

            modelBuilder.Entity("Varejo.Models.TipoMovimento", b =>
                {
                    b.Property<int>("IdTipoMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMovimento"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DescricaoTipoMovimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EspecieMovimentoId")
                        .HasColumnType("int");

                    b.HasKey("IdTipoMovimento");

                    b.HasIndex("EspecieMovimentoId");

                    b.ToTable("TiposMovimento");
                });

            modelBuilder.Entity("Varejo.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DescricaoTipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TiposUsuario");
                });

            modelBuilder.Entity("Varejo.Models.TituloFinanceiro", b =>
                {
                    b.Property<int>("IdTituloFinanceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTituloFinanceiro"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Documento")
                        .HasColumnType("int");

                    b.Property<int>("EspecieTituloId")
                        .HasColumnType("int");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Parcela")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("PrazoPagamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Quitado")
                        .HasColumnType("bit");

                    b.Property<int?>("RecebimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorAberto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("IdTituloFinanceiro");

                    b.HasIndex("EspecieTituloId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("PrazoPagamentoId");

                    b.HasIndex("RecebimentoId");

                    b.HasIndex("VendaId");

                    b.ToTable("TitulosFinanceiro");
                });

            modelBuilder.Entity("Varejo.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.HasIndex("TipoUsuarioId");

                    b.HasIndex("nomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Varejo.Models.UsuarioRelatorioFavorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoRelatorio")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "CodigoRelatorio")
                        .IsUnique();

                    b.ToTable("UsuarioRelatoriosFavoritos");
                });

            modelBuilder.Entity("Varejo.Models.Validade", b =>
                {
                    b.Property<int>("IdValidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValidade"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmEstoque")
                        .HasColumnType("bit");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("IdValidade");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Validades");
                });

            modelBuilder.Entity("Varejo.Models.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenda"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DescontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int?>("PrazoPagamentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdVenda");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("PrazoPagamentoId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Varejo.Models.VendaItem", b =>
                {
                    b.Property<int>("IdVendaItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVendaItem"));

                    b.Property<decimal>("DescontoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoEmbalagemId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("IdVendaItem");

                    b.HasIndex("ProdutoEmbalagemId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("VendasItem");
                });

            modelBuilder.Entity("Parametro", b =>
                {
                    b.HasOne("Varejo.Models.TipoMovimento", "TipoMovimentoAvaria")
                        .WithMany()
                        .HasForeignKey("TipoMovimentoAvariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.TipoMovimento", "TipoMovimentoCompra")
                        .WithMany()
                        .HasForeignKey("TipoMovimentoCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.TipoMovimento", "TipoMovimentoEntradaBonificacao")
                        .WithMany()
                        .HasForeignKey("TipoMovimentoEntradaBonificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.TipoMovimento", "TipoMovimentoVenda")
                        .WithMany()
                        .HasForeignKey("TipoMovimentoVendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMovimentoAvaria");

                    b.Navigation("TipoMovimentoCompra");

                    b.Navigation("TipoMovimentoEntradaBonificacao");

                    b.Navigation("TipoMovimentoVenda");
                });

            modelBuilder.Entity("RecebimentoItem", b =>
                {
                    b.HasOne("Varejo.Models.ProdutoEmbalagem", "ProdutoEmbalagem")
                        .WithMany()
                        .HasForeignKey("ProdutoEmbalagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Recebimento", "Recebimento")
                        .WithMany("Itens")
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("ProdutoEmbalagem");

                    b.Navigation("Recebimento");
                });

            modelBuilder.Entity("Varejo.Models.Endereco", b =>
                {
                    b.HasOne("Varejo.Models.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Varejo.Models.EstoqueConfig", b =>
                {
                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithOne("EstoqueConfig")
                        .HasForeignKey("Varejo.Models.EstoqueConfig", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Varejo.Models.Familia", b =>
                {
                    b.HasOne("Varejo.Models.Categoria", "Categoria")
                        .WithMany("Familias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Marca", "Marca")
                        .WithMany("Familias")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Varejo.Models.FornecedorFamilia", b =>
                {
                    b.HasOne("Varejo.Models.Familia", "Familia")
                        .WithMany("FornecedoresFamilia")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Varejo.Models.HistoricoPreco", b =>
                {
                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Varejo.Models.HistoricoProduto", b =>
                {
                    b.HasOne("Varejo.Models.EspecieMovimento", "EspecieMovimento")
                        .WithMany()
                        .HasForeignKey("EspecieMovimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Movimento", "Movimento")
                        .WithMany()
                        .HasForeignKey("MovimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany("Historicos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.TipoMovimento", "TipoMovimento")
                        .WithMany()
                        .HasForeignKey("TipoMovimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EspecieMovimento");

                    b.Navigation("Movimento");

                    b.Navigation("Produto");

                    b.Navigation("TipoMovimento");
                });

            modelBuilder.Entity("Varejo.Models.InventarioItem", b =>
                {
                    b.HasOne("Varejo.Models.Inventario", "Inventario")
                        .WithMany("Itens")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.ProdutoEmbalagem", "ProdutoEmbalagem")
                        .WithMany()
                        .HasForeignKey("ProdutoEmbalagemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");

                    b.Navigation("Produto");

                    b.Navigation("ProdutoEmbalagem");
                });

            modelBuilder.Entity("Varejo.Models.Movimento", b =>
                {
                    b.HasOne("Varejo.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Recebimento", "Recebimento")
                        .WithMany()
                        .HasForeignKey("RecebimentoId");

                    b.HasOne("Varejo.Models.TipoMovimento", "TipoMovimento")
                        .WithMany()
                        .HasForeignKey("TipoMovimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId");

                    b.Navigation("Pessoa");

                    b.Navigation("Recebimento");

                    b.Navigation("TipoMovimento");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Varejo.Models.PagamentoTitulo", b =>
                {
                    b.HasOne("Varejo.Models.TituloFinanceiro", "TituloFinanceiro")
                        .WithMany("Pagamentos")
                        .HasForeignKey("TituloFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TituloFinanceiro");
                });

            modelBuilder.Entity("Varejo.Models.Produto", b =>
                {
                    b.HasOne("Varejo.Models.Familia", "Familia")
                        .WithMany("Produtos")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoCusto", b =>
                {
                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Recebimento", "Recebimento")
                        .WithMany()
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Recebimento");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoEmbalagem", b =>
                {
                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany("ProdutosEmbalagem")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.TipoEmbalagem", "TipoEmbalagem")
                        .WithMany("ProdutosEmbalagem")
                        .HasForeignKey("TipoEmbalagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("TipoEmbalagem");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoFornecedorVinculo", b =>
                {
                    b.HasOne("Varejo.Models.Pessoa", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Varejo.Models.ProdutoMovimento", b =>
                {
                    b.HasOne("Varejo.Models.Movimento", "Movimento")
                        .WithMany("ProdutosMovimento")
                        .HasForeignKey("MovimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.ProdutoEmbalagem", "ProdutoEmbalagem")
                        .WithMany()
                        .HasForeignKey("ProdutoEmbalagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movimento");

                    b.Navigation("Produto");

                    b.Navigation("ProdutoEmbalagem");
                });

            modelBuilder.Entity("Varejo.Models.Recebimento", b =>
                {
                    b.HasOne("Varejo.Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId");

                    b.HasOne("Varejo.Models.Pessoa", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.PrazoPagamento", "PrazoPagamento")
                        .WithMany()
                        .HasForeignKey("PrazoPagamentoId");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Fornecedor");

                    b.Navigation("PrazoPagamento");
                });

            modelBuilder.Entity("Varejo.Models.RecebimentoXmlLog", b =>
                {
                    b.HasOne("Varejo.Models.Recebimento", "Recebimento")
                        .WithMany()
                        .HasForeignKey("RecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recebimento");
                });

            modelBuilder.Entity("Varejo.Models.TipoMovimento", b =>
                {
                    b.HasOne("Varejo.Models.EspecieMovimento", "EspecieMovimento")
                        .WithMany("TiposMovimento")
                        .HasForeignKey("EspecieMovimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EspecieMovimento");
                });

            modelBuilder.Entity("Varejo.Models.TituloFinanceiro", b =>
                {
                    b.HasOne("Varejo.Models.EspecieTitulo", "EspecieTitulo")
                        .WithMany("Titulos")
                        .HasForeignKey("EspecieTituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.FormaPagamento", "FormaPagamento")
                        .WithMany("Titulos")
                        .HasForeignKey("FormaPagamentoId");

                    b.HasOne("Varejo.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.HasOne("Varejo.Models.PrazoPagamento", "PrazoPagamento")
                        .WithMany("Titulos")
                        .HasForeignKey("PrazoPagamentoId");

                    b.HasOne("Varejo.Models.Recebimento", "Recebimento")
                        .WithMany()
                        .HasForeignKey("RecebimentoId");

                    b.HasOne("Varejo.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId");

                    b.Navigation("EspecieTitulo");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Pessoa");

                    b.Navigation("PrazoPagamento");

                    b.Navigation("Recebimento");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Varejo.Models.Usuario", b =>
                {
                    b.HasOne("Varejo.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Varejo.Models.UsuarioRelatorioFavorito", b =>
                {
                    b.HasOne("Varejo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Varejo.Models.Validade", b =>
                {
                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Varejo.Models.Venda", b =>
                {
                    b.HasOne("Varejo.Models.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.PrazoPagamento", "PrazoPagamento")
                        .WithMany()
                        .HasForeignKey("PrazoPagamentoId");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Pessoa");

                    b.Navigation("PrazoPagamento");
                });

            modelBuilder.Entity("Varejo.Models.VendaItem", b =>
                {
                    b.HasOne("Varejo.Models.ProdutoEmbalagem", "ProdutoEmbalagem")
                        .WithMany()
                        .HasForeignKey("ProdutoEmbalagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varejo.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("ProdutoEmbalagem");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Varejo.Models.Categoria", b =>
                {
                    b.Navigation("Familias");
                });

            modelBuilder.Entity("Varejo.Models.EspecieMovimento", b =>
                {
                    b.Navigation("TiposMovimento");
                });

            modelBuilder.Entity("Varejo.Models.EspecieTitulo", b =>
                {
                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("Varejo.Models.Familia", b =>
                {
                    b.Navigation("FornecedoresFamilia");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Varejo.Models.FormaPagamento", b =>
                {
                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("Varejo.Models.Inventario", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Varejo.Models.Marca", b =>
                {
                    b.Navigation("Familias");
                });

            modelBuilder.Entity("Varejo.Models.Movimento", b =>
                {
                    b.Navigation("ProdutosMovimento");
                });

            modelBuilder.Entity("Varejo.Models.Pessoa", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("Varejo.Models.PrazoPagamento", b =>
                {
                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("Varejo.Models.Produto", b =>
                {
                    b.Navigation("EstoqueConfig")
                        .IsRequired();

                    b.Navigation("Historicos");

                    b.Navigation("ProdutosEmbalagem");
                });

            modelBuilder.Entity("Varejo.Models.Recebimento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Varejo.Models.TipoEmbalagem", b =>
                {
                    b.Navigation("ProdutosEmbalagem");
                });

            modelBuilder.Entity("Varejo.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Varejo.Models.TituloFinanceiro", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Varejo.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
